name: Testing a name with input

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Just the name"
        required: true

jobs:
  echo:
    name: Echoing stuff for ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello, from ${{ inputs.name }}!"
